import { StyleSheet } from "react-native";

const SettingStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  name: {
    flex: 0.4,
  },
  ImageBackground: {
    width: "100%",
    height: "100%",
  },
  timer: {
    width: "35%",
    height: "60%",
    position: "absolute",
    bottom: "5%",
    alignItems: "center",
  },
  btns_timer: {
    marginTop: -80,
    width: "70%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  gif: { width: "70%", height: "70%" },
  btn_timer_up: {
    backgroundColor: "white",
    width: 45,
    height: 45,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    transform: [{ rotate: "45deg" }],
  },
  btn_timer_down: {
    marginTop: 90,
    backgroundColor: "white",
    width: 45,
    height: 45,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    transform: [{ rotate: "45deg" }],
  },
  txt_timer: {
    width: 40,
    height: 40,
    fontWeight: "700",
    fontSize: 30,
    textAlign: "center",
    transform: [{ rotate: "-45deg" }],
  },
  num_card: {
    width: "33%",
    height: "60%",
    position: "absolute",
    bottom: "5%",
    left: "35%",
  },
  btn_img_box: {
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
    height: "50%",
  },
  img_box: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  gling: {
    width: "32%",
    height: "25%",
    position: "absolute",
    bottom: "40%",
    left: "68%",
    alignItems: "center",
    justifyContent: "center",
  },
  view_btn_play: {
    width: "32%",
    height: "40%",
    position: "absolute",
    bottom: 0,
    left: "68%",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  btn_play: {
    width: "70%",
    height: "30%",
    backgroundColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    borderColor: "black",
    borderWidth: 4,
    display: "flex",
    flexDirection: "row",
  },
});
export default SettingStyles;
