import { StyleSheet } from "react-native";

const SettingStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  name: {
    flex: 0.2,
  },
  ImageBackground: {
    width: "100%",
    height: "100%",
  },
  timer: {
    width: "40%",
    height: "70%",
    position: "absolute",
    bottom: "10%",
    alignItems: "center",
  },
  btns_timer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  gif: { width: "80%", height: "80%" },
  btn_timer: {
    backgroundColor: "white",
    width: 45,
    height: 45,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    transform: [{ rotate: "45deg" }],
  },
  txt_timer: {
    width: 40,
    height: 40,
    fontWeight: "700",
    fontSize: 30,
    textAlign: "center",
    transform: [{ rotate: "-45deg" }],
  },
  num_card: {
    width: "30%",
    height: "70%",
    position: "absolute",
    bottom: "5%",
    left: "40%",
  },
  btn_img_box: {
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
    height: "50%",
  },
  img_box: {
    width: 100,
    height: 100,
    borderRadius: 10,
  },
  gling: {
    width: "30%",
    height: "50%",
    position: "absolute",
    bottom: "25%",
    left: "70%",
    alignItems: "center",
    justifyContent: "center",
  },
  view_btn_play: {
    width: "30%",
    height: "25%",
    position: "absolute",
    bottom: 0,
    left: "70%",
    alignItems: "center",
    justifyContent: "center",
  },
  btn_play: {
    width: "70%",
    height: "50%",
    backgroundColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    borderColor: "black",
    borderWidth: 4,
    display: "flex",
    flexDirection: "row",
  },
});
export default SettingStyles;
